apiVersion: v2
name: argocd-config
description: Chart to deploy ArgoCD configuration (including the argocd-apps chart)
type: application
version: 1.0.11
appVersion: "1.0"
maintainers:
  - name: WBstack
    url: https://github.com/wbstack
