apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: tool-quickstatements
version: "0.4.0"
home: https://github.com/wbstack
maintainers:
  - name: WBstack
    url: https://github.com/wbstack
