repoUrls:
  deploy: https://github.com/wmde/wbaas-deploy
  wbstack: https://wbstack.github.io/charts
  bitnami: https://charts.bitnami.com/bitnami
clusterUrl: https://kubernetes.default.svc
environment: production

chartVersions:
  wbaasUi: 0.4.0
  wbaasApi: 0.32.1
  redis: redis/17.3.8
  redis2: redis/19.6.4
# "inherits" values from argocd-config chart
