apiVersion: v2
name: tool-querybuilder
description: A Helm chart for deploying the Wikidata query builder https://gerrit.wikimedia.org/g/wikidata/query-builder
type: application
version: 0.3.0
appVersion: 1.0.0

maintainers:
  - name: WBstack
    url: https://github.com/wbstack
